// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class AnchorLiveStatusNotify;
@class AnchorLiveStatusNotifyBuilder;
@class BannerNotify;
@class BannerNotifyBuilder;
@class ChatNotify;
@class ChatNotifyBuilder;
@class ChatUp;
@class ChatUpBuilder;
@class FollowNotify;
@class FollowNotifyBuilder;
@class GiftNotify;
@class GiftNotifyBuilder;
@class GiftUp;
@class GiftUpBuilder;
@class KickoutNotify;
@class KickoutNotifyBuilder;
@class LinkAccept;
@class LinkAcceptBuilder;
@class LinkApply;
@class LinkApplyBuilder;
@class LinkApplyCountChg;
@class LinkApplyCountChgBuilder;
@class LinkBroadcast;
@class LinkBroadcastBuilder;
@class LinkCancel;
@class LinkCancelBuilder;
@class LinkClose;
@class LinkCloseBuilder;
@class LiveData;
@class LiveDataBuilder;
@class LoginReq;
@class LoginReqBuilder;
@class LoginRsp;
@class LoginRspBuilder;
@class ManagerNotify;
@class ManagerNotifyBuilder;
@class RedEnvelopeNotify;
@class RedEnvelopeNotifyBuilder;
@class RetetionAttr;
@class RetetionAttrBuilder;
@class RoomAttr;
@class RoomAttrBuilder;
@class RoomJoinNotify;
@class RoomJoinNotifyBuilder;
@class RoomJoinNotifyUp;
@class RoomJoinNotifyUpBuilder;
@class RoomJoinReq;
@class RoomJoinReqBuilder;
@class RoomJoinRsp;
@class RoomJoinRspBuilder;
@class RoomLeaveReq;
@class RoomLeaveReqBuilder;
@class RoomUpdateNotify;
@class RoomUpdateNotifyBuilder;
@class SharedNotify;
@class SharedNotifyBuilder;
@class User;
@class UserAttrNotify;
@class UserAttrNotifyBuilder;
@class UserBuilder;
@class UserLevelUpNotify;
@class UserLevelUpNotifyBuilder;
@class ZanNotify;
@class ZanNotifyBuilder;
@class ZanUp;
@class ZanUpBuilder;



@interface TestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define User_uid @"uid"
#define User_gender @"gender"
#define User_verified @"verified"
#define User_exp @"exp"
#define User_level @"level"
#define User_authed @"authed"
#define User_status @"status"
#define User_nickname @"nickname"
#define User_guard @"guard"
#define User_rider @"rider"
#define User_portrait @"portrait"
@interface User : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasGender_:1;
  BOOL hasVerified_:1;
  BOOL hasExp_:1;
  BOOL hasLevel_:1;
  BOOL hasAuthed_:1;
  BOOL hasStatus_:1;
  BOOL hasGuard_:1;
  BOOL hasRider_:1;
  BOOL hasNickname_:1;
  BOOL hasPortrait_:1;
  SInt32 uid;
  SInt32 gender;
  SInt32 verified;
  SInt32 exp;
  SInt32 level;
  SInt32 authed;
  SInt32 status;
  SInt32 guard;
  SInt32 rider;
  NSString* nickname;
  NSString* portrait;
}
- (BOOL) hasUid;
- (BOOL) hasGender;
- (BOOL) hasVerified;
- (BOOL) hasExp;
- (BOOL) hasLevel;
- (BOOL) hasAuthed;
- (BOOL) hasStatus;
- (BOOL) hasNickname;
- (BOOL) hasGuard;
- (BOOL) hasRider;
- (BOOL) hasPortrait;
@property (readonly) SInt32 uid;
@property (readonly) SInt32 gender;
@property (readonly) SInt32 verified;
@property (readonly) SInt32 exp;
@property (readonly) SInt32 level;
@property (readonly) SInt32 authed;
@property (readonly) SInt32 status;
@property (readonly, strong) NSString* nickname;
@property (readonly) SInt32 guard;
@property (readonly) SInt32 rider;
@property (readonly, strong) NSString* portrait;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBuilder*) builder;
+ (UserBuilder*) builder;
+ (UserBuilder*) builderWithPrototype:(User*) prototype;
- (UserBuilder*) toBuilder;

+ (User*) parseFromData:(NSData*) data;
+ (User*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (User*) parseFromInputStream:(NSInputStream*) input;
+ (User*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (User*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (User*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBuilder : PBGeneratedMessageBuilder {
@private
  User* resultUser;
}

- (User*) defaultInstance;

- (UserBuilder*) clear;
- (UserBuilder*) clone;

- (User*) build;
- (User*) buildPartial;

- (UserBuilder*) mergeFrom:(User*) other;
- (UserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (SInt32) uid;
- (UserBuilder*) setUid:(SInt32) value;
- (UserBuilder*) clearUid;

- (BOOL) hasGender;
- (SInt32) gender;
- (UserBuilder*) setGender:(SInt32) value;
- (UserBuilder*) clearGender;

- (BOOL) hasVerified;
- (SInt32) verified;
- (UserBuilder*) setVerified:(SInt32) value;
- (UserBuilder*) clearVerified;

- (BOOL) hasExp;
- (SInt32) exp;
- (UserBuilder*) setExp:(SInt32) value;
- (UserBuilder*) clearExp;

- (BOOL) hasLevel;
- (SInt32) level;
- (UserBuilder*) setLevel:(SInt32) value;
- (UserBuilder*) clearLevel;

- (BOOL) hasAuthed;
- (SInt32) authed;
- (UserBuilder*) setAuthed:(SInt32) value;
- (UserBuilder*) clearAuthed;

- (BOOL) hasStatus;
- (SInt32) status;
- (UserBuilder*) setStatus:(SInt32) value;
- (UserBuilder*) clearStatus;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (UserBuilder*) setNickname:(NSString*) value;
- (UserBuilder*) clearNickname;

- (BOOL) hasGuard;
- (SInt32) guard;
- (UserBuilder*) setGuard:(SInt32) value;
- (UserBuilder*) clearGuard;

- (BOOL) hasRider;
- (SInt32) rider;
- (UserBuilder*) setRider:(SInt32) value;
- (UserBuilder*) clearRider;

- (BOOL) hasPortrait;
- (NSString*) portrait;
- (UserBuilder*) setPortrait:(NSString*) value;
- (UserBuilder*) clearPortrait;
@end

#define LiveData_online @"online"
#define LiveData_starlight @"starlight"
#define LiveData_fight @"fight"
#define LiveData_status @"status"
#define LiveData_views @"views"
#define LiveData_duration @"duration"
#define LiveData_maxOnline @"maxOnline"
@interface LiveData : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOnline_:1;
  BOOL hasStarlight_:1;
  BOOL hasFight_:1;
  BOOL hasStatus_:1;
  BOOL hasViews_:1;
  BOOL hasDuration_:1;
  BOOL hasMaxOnline_:1;
  SInt32 online;
  SInt32 starlight;
  SInt32 fight;
  SInt32 status;
  SInt32 views;
  SInt32 duration;
  SInt32 maxOnline;
}
- (BOOL) hasOnline;
- (BOOL) hasStarlight;
- (BOOL) hasFight;
- (BOOL) hasStatus;
- (BOOL) hasViews;
- (BOOL) hasDuration;
- (BOOL) hasMaxOnline;
@property (readonly) SInt32 online;
@property (readonly) SInt32 starlight;
@property (readonly) SInt32 fight;
@property (readonly) SInt32 status;
@property (readonly) SInt32 views;
@property (readonly) SInt32 duration;
@property (readonly) SInt32 maxOnline;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LiveDataBuilder*) builder;
+ (LiveDataBuilder*) builder;
+ (LiveDataBuilder*) builderWithPrototype:(LiveData*) prototype;
- (LiveDataBuilder*) toBuilder;

+ (LiveData*) parseFromData:(NSData*) data;
+ (LiveData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LiveData*) parseFromInputStream:(NSInputStream*) input;
+ (LiveData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LiveData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LiveData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LiveDataBuilder : PBGeneratedMessageBuilder {
@private
  LiveData* resultLiveData;
}

- (LiveData*) defaultInstance;

- (LiveDataBuilder*) clear;
- (LiveDataBuilder*) clone;

- (LiveData*) build;
- (LiveData*) buildPartial;

- (LiveDataBuilder*) mergeFrom:(LiveData*) other;
- (LiveDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LiveDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOnline;
- (SInt32) online;
- (LiveDataBuilder*) setOnline:(SInt32) value;
- (LiveDataBuilder*) clearOnline;

- (BOOL) hasStarlight;
- (SInt32) starlight;
- (LiveDataBuilder*) setStarlight:(SInt32) value;
- (LiveDataBuilder*) clearStarlight;

- (BOOL) hasFight;
- (SInt32) fight;
- (LiveDataBuilder*) setFight:(SInt32) value;
- (LiveDataBuilder*) clearFight;

- (BOOL) hasStatus;
- (SInt32) status;
- (LiveDataBuilder*) setStatus:(SInt32) value;
- (LiveDataBuilder*) clearStatus;

- (BOOL) hasViews;
- (SInt32) views;
- (LiveDataBuilder*) setViews:(SInt32) value;
- (LiveDataBuilder*) clearViews;

- (BOOL) hasDuration;
- (SInt32) duration;
- (LiveDataBuilder*) setDuration:(SInt32) value;
- (LiveDataBuilder*) clearDuration;

- (BOOL) hasMaxOnline;
- (SInt32) maxOnline;
- (LiveDataBuilder*) setMaxOnline:(SInt32) value;
- (LiveDataBuilder*) clearMaxOnline;
@end

#define RoomAttr_priv @"priv"
#define RoomAttr_guard @"guard"
@interface RoomAttr : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPriv_:1;
  BOOL hasGuard_:1;
  SInt32 priv;
  SInt32 guard;
}
- (BOOL) hasPriv;
- (BOOL) hasGuard;
@property (readonly) SInt32 priv;
@property (readonly) SInt32 guard;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomAttrBuilder*) builder;
+ (RoomAttrBuilder*) builder;
+ (RoomAttrBuilder*) builderWithPrototype:(RoomAttr*) prototype;
- (RoomAttrBuilder*) toBuilder;

+ (RoomAttr*) parseFromData:(NSData*) data;
+ (RoomAttr*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomAttr*) parseFromInputStream:(NSInputStream*) input;
+ (RoomAttr*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomAttr*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomAttr*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomAttrBuilder : PBGeneratedMessageBuilder {
@private
  RoomAttr* resultRoomAttr;
}

- (RoomAttr*) defaultInstance;

- (RoomAttrBuilder*) clear;
- (RoomAttrBuilder*) clone;

- (RoomAttr*) build;
- (RoomAttr*) buildPartial;

- (RoomAttrBuilder*) mergeFrom:(RoomAttr*) other;
- (RoomAttrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomAttrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPriv;
- (SInt32) priv;
- (RoomAttrBuilder*) setPriv:(SInt32) value;
- (RoomAttrBuilder*) clearPriv;

- (BOOL) hasGuard;
- (SInt32) guard;
- (RoomAttrBuilder*) setGuard:(SInt32) value;
- (RoomAttrBuilder*) clearGuard;
@end

#define RetetionAttr_aliveTime @"aliveTime"
#define RetetionAttr_nowTime @"nowTime"
#define RetetionAttr_startTime @"startTime"
#define RetetionAttr_id @"id"
@interface RetetionAttr : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAliveTime_:1;
  BOOL hasNowTime_:1;
  BOOL hasStartTime_:1;
  BOOL hasId_:1;
  SInt32 aliveTime;
  SInt32 nowTime;
  SInt32 startTime;
  SInt32 id;
}
- (BOOL) hasAliveTime;
- (BOOL) hasNowTime;
- (BOOL) hasStartTime;
- (BOOL) hasId;
@property (readonly) SInt32 aliveTime;
@property (readonly) SInt32 nowTime;
@property (readonly) SInt32 startTime;
@property (readonly) SInt32 id;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RetetionAttrBuilder*) builder;
+ (RetetionAttrBuilder*) builder;
+ (RetetionAttrBuilder*) builderWithPrototype:(RetetionAttr*) prototype;
- (RetetionAttrBuilder*) toBuilder;

+ (RetetionAttr*) parseFromData:(NSData*) data;
+ (RetetionAttr*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetetionAttr*) parseFromInputStream:(NSInputStream*) input;
+ (RetetionAttr*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RetetionAttr*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RetetionAttr*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RetetionAttrBuilder : PBGeneratedMessageBuilder {
@private
  RetetionAttr* resultRetetionAttr;
}

- (RetetionAttr*) defaultInstance;

- (RetetionAttrBuilder*) clear;
- (RetetionAttrBuilder*) clone;

- (RetetionAttr*) build;
- (RetetionAttr*) buildPartial;

- (RetetionAttrBuilder*) mergeFrom:(RetetionAttr*) other;
- (RetetionAttrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RetetionAttrBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAliveTime;
- (SInt32) aliveTime;
- (RetetionAttrBuilder*) setAliveTime:(SInt32) value;
- (RetetionAttrBuilder*) clearAliveTime;

- (BOOL) hasNowTime;
- (SInt32) nowTime;
- (RetetionAttrBuilder*) setNowTime:(SInt32) value;
- (RetetionAttrBuilder*) clearNowTime;

- (BOOL) hasStartTime;
- (SInt32) startTime;
- (RetetionAttrBuilder*) setStartTime:(SInt32) value;
- (RetetionAttrBuilder*) clearStartTime;

- (BOOL) hasId;
- (SInt32) id;
- (RetetionAttrBuilder*) setId:(SInt32) value;
- (RetetionAttrBuilder*) clearId;
@end

#define LoginReq_uid @"uid"
#define LoginReq_pwd @"pwd"
#define LoginReq_devid @"devid"
#define LoginReq_app @"app"
#define LoginReq_rt @"rt"
#define LoginReq_vk @"vk"
#define LoginReq_ver @"ver"
#define LoginReq_channel @"channel"
@interface LoginReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRt_:1;
  BOOL hasUid_:1;
  BOOL hasPwd_:1;
  BOOL hasDevid_:1;
  BOOL hasApp_:1;
  BOOL hasVk_:1;
  BOOL hasVer_:1;
  BOOL hasChannel_:1;
  SInt64 rt;
  SInt32 uid;
  NSString* pwd;
  NSString* devid;
  NSString* app;
  NSString* vk;
  NSString* ver;
  NSString* channel;
}
- (BOOL) hasUid;
- (BOOL) hasPwd;
- (BOOL) hasDevid;
- (BOOL) hasApp;
- (BOOL) hasRt;
- (BOOL) hasVk;
- (BOOL) hasVer;
- (BOOL) hasChannel;
@property (readonly) SInt32 uid;
@property (readonly, strong) NSString* pwd;
@property (readonly, strong) NSString* devid;
@property (readonly, strong) NSString* app;
@property (readonly) SInt64 rt;
@property (readonly, strong) NSString* vk;
@property (readonly, strong) NSString* ver;
@property (readonly, strong) NSString* channel;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoginReqBuilder*) builder;
+ (LoginReqBuilder*) builder;
+ (LoginReqBuilder*) builderWithPrototype:(LoginReq*) prototype;
- (LoginReqBuilder*) toBuilder;

+ (LoginReq*) parseFromData:(NSData*) data;
+ (LoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (LoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoginReqBuilder : PBGeneratedMessageBuilder {
@private
  LoginReq* resultLoginReq;
}

- (LoginReq*) defaultInstance;

- (LoginReqBuilder*) clear;
- (LoginReqBuilder*) clone;

- (LoginReq*) build;
- (LoginReq*) buildPartial;

- (LoginReqBuilder*) mergeFrom:(LoginReq*) other;
- (LoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoginReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (SInt32) uid;
- (LoginReqBuilder*) setUid:(SInt32) value;
- (LoginReqBuilder*) clearUid;

- (BOOL) hasPwd;
- (NSString*) pwd;
- (LoginReqBuilder*) setPwd:(NSString*) value;
- (LoginReqBuilder*) clearPwd;

- (BOOL) hasDevid;
- (NSString*) devid;
- (LoginReqBuilder*) setDevid:(NSString*) value;
- (LoginReqBuilder*) clearDevid;

- (BOOL) hasApp;
- (NSString*) app;
- (LoginReqBuilder*) setApp:(NSString*) value;
- (LoginReqBuilder*) clearApp;

- (BOOL) hasRt;
- (SInt64) rt;
- (LoginReqBuilder*) setRt:(SInt64) value;
- (LoginReqBuilder*) clearRt;

- (BOOL) hasVk;
- (NSString*) vk;
- (LoginReqBuilder*) setVk:(NSString*) value;
- (LoginReqBuilder*) clearVk;

- (BOOL) hasVer;
- (NSString*) ver;
- (LoginReqBuilder*) setVer:(NSString*) value;
- (LoginReqBuilder*) clearVer;

- (BOOL) hasChannel;
- (NSString*) channel;
- (LoginReqBuilder*) setChannel:(NSString*) value;
- (LoginReqBuilder*) clearChannel;
@end

#define LoginRsp_status @"status"
#define LoginRsp_uid @"uid"
@interface LoginRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  BOOL hasUid_:1;
  SInt32 status;
  SInt32 uid;
}
- (BOOL) hasStatus;
- (BOOL) hasUid;
@property (readonly) SInt32 status;
@property (readonly) SInt32 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoginRspBuilder*) builder;
+ (LoginRspBuilder*) builder;
+ (LoginRspBuilder*) builderWithPrototype:(LoginRsp*) prototype;
- (LoginRspBuilder*) toBuilder;

+ (LoginRsp*) parseFromData:(NSData*) data;
+ (LoginRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginRsp*) parseFromInputStream:(NSInputStream*) input;
+ (LoginRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoginRspBuilder : PBGeneratedMessageBuilder {
@private
  LoginRsp* resultLoginRsp;
}

- (LoginRsp*) defaultInstance;

- (LoginRspBuilder*) clear;
- (LoginRspBuilder*) clone;

- (LoginRsp*) build;
- (LoginRsp*) buildPartial;

- (LoginRspBuilder*) mergeFrom:(LoginRsp*) other;
- (LoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoginRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (SInt32) status;
- (LoginRspBuilder*) setStatus:(SInt32) value;
- (LoginRspBuilder*) clearStatus;

- (BOOL) hasUid;
- (SInt32) uid;
- (LoginRspBuilder*) setUid:(SInt32) value;
- (LoginRspBuilder*) clearUid;
@end

#define RoomJoinReq_owid @"owid"
@interface RoomJoinReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  SInt32 owid;
}
- (BOOL) hasOwid;
@property (readonly) SInt32 owid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomJoinReqBuilder*) builder;
+ (RoomJoinReqBuilder*) builder;
+ (RoomJoinReqBuilder*) builderWithPrototype:(RoomJoinReq*) prototype;
- (RoomJoinReqBuilder*) toBuilder;

+ (RoomJoinReq*) parseFromData:(NSData*) data;
+ (RoomJoinReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinReq*) parseFromInputStream:(NSInputStream*) input;
+ (RoomJoinReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomJoinReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomJoinReqBuilder : PBGeneratedMessageBuilder {
@private
  RoomJoinReq* resultRoomJoinReq;
}

- (RoomJoinReq*) defaultInstance;

- (RoomJoinReqBuilder*) clear;
- (RoomJoinReqBuilder*) clone;

- (RoomJoinReq*) build;
- (RoomJoinReq*) buildPartial;

- (RoomJoinReqBuilder*) mergeFrom:(RoomJoinReq*) other;
- (RoomJoinReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomJoinReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomJoinReqBuilder*) setOwid:(SInt32) value;
- (RoomJoinReqBuilder*) clearOwid;
@end

#define RoomJoinRsp_owid @"owid"
#define RoomJoinRsp_code @"code"
#define RoomJoinRsp_roomAttr @"roomAttr"
#define RoomJoinRsp_liveData @"liveData"
@interface RoomJoinRsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasCode_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasLiveData_:1;
  SInt32 owid;
  SInt32 code;
  RoomAttr* roomAttr;
  LiveData* liveData;
}
- (BOOL) hasOwid;
- (BOOL) hasCode;
- (BOOL) hasRoomAttr;
- (BOOL) hasLiveData;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 code;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) LiveData* liveData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomJoinRspBuilder*) builder;
+ (RoomJoinRspBuilder*) builder;
+ (RoomJoinRspBuilder*) builderWithPrototype:(RoomJoinRsp*) prototype;
- (RoomJoinRspBuilder*) toBuilder;

+ (RoomJoinRsp*) parseFromData:(NSData*) data;
+ (RoomJoinRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinRsp*) parseFromInputStream:(NSInputStream*) input;
+ (RoomJoinRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomJoinRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomJoinRspBuilder : PBGeneratedMessageBuilder {
@private
  RoomJoinRsp* resultRoomJoinRsp;
}

- (RoomJoinRsp*) defaultInstance;

- (RoomJoinRspBuilder*) clear;
- (RoomJoinRspBuilder*) clone;

- (RoomJoinRsp*) build;
- (RoomJoinRsp*) buildPartial;

- (RoomJoinRspBuilder*) mergeFrom:(RoomJoinRsp*) other;
- (RoomJoinRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomJoinRspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomJoinRspBuilder*) setOwid:(SInt32) value;
- (RoomJoinRspBuilder*) clearOwid;

- (BOOL) hasCode;
- (SInt32) code;
- (RoomJoinRspBuilder*) setCode:(SInt32) value;
- (RoomJoinRspBuilder*) clearCode;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (RoomJoinRspBuilder*) setRoomAttr:(RoomAttr*) value;
- (RoomJoinRspBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (RoomJoinRspBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (RoomJoinRspBuilder*) clearRoomAttr;

- (BOOL) hasLiveData;
- (LiveData*) liveData;
- (RoomJoinRspBuilder*) setLiveData:(LiveData*) value;
- (RoomJoinRspBuilder*) setLiveDataBuilder:(LiveDataBuilder*) builderForValue;
- (RoomJoinRspBuilder*) mergeLiveData:(LiveData*) value;
- (RoomJoinRspBuilder*) clearLiveData;
@end

#define RoomJoinNotifyUp_owid @"owid"
@interface RoomJoinNotifyUp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  SInt32 owid;
}
- (BOOL) hasOwid;
@property (readonly) SInt32 owid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomJoinNotifyUpBuilder*) builder;
+ (RoomJoinNotifyUpBuilder*) builder;
+ (RoomJoinNotifyUpBuilder*) builderWithPrototype:(RoomJoinNotifyUp*) prototype;
- (RoomJoinNotifyUpBuilder*) toBuilder;

+ (RoomJoinNotifyUp*) parseFromData:(NSData*) data;
+ (RoomJoinNotifyUp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinNotifyUp*) parseFromInputStream:(NSInputStream*) input;
+ (RoomJoinNotifyUp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinNotifyUp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomJoinNotifyUp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomJoinNotifyUpBuilder : PBGeneratedMessageBuilder {
@private
  RoomJoinNotifyUp* resultRoomJoinNotifyUp;
}

- (RoomJoinNotifyUp*) defaultInstance;

- (RoomJoinNotifyUpBuilder*) clear;
- (RoomJoinNotifyUpBuilder*) clone;

- (RoomJoinNotifyUp*) build;
- (RoomJoinNotifyUp*) buildPartial;

- (RoomJoinNotifyUpBuilder*) mergeFrom:(RoomJoinNotifyUp*) other;
- (RoomJoinNotifyUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomJoinNotifyUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomJoinNotifyUpBuilder*) setOwid:(SInt32) value;
- (RoomJoinNotifyUpBuilder*) clearOwid;
@end

#define RoomJoinNotify_owid @"owid"
#define RoomJoinNotify_roomAttr @"roomAttr"
#define RoomJoinNotify_user @"user"
@interface RoomJoinNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomJoinNotifyBuilder*) builder;
+ (RoomJoinNotifyBuilder*) builder;
+ (RoomJoinNotifyBuilder*) builderWithPrototype:(RoomJoinNotify*) prototype;
- (RoomJoinNotifyBuilder*) toBuilder;

+ (RoomJoinNotify*) parseFromData:(NSData*) data;
+ (RoomJoinNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinNotify*) parseFromInputStream:(NSInputStream*) input;
+ (RoomJoinNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomJoinNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomJoinNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomJoinNotifyBuilder : PBGeneratedMessageBuilder {
@private
  RoomJoinNotify* resultRoomJoinNotify;
}

- (RoomJoinNotify*) defaultInstance;

- (RoomJoinNotifyBuilder*) clear;
- (RoomJoinNotifyBuilder*) clone;

- (RoomJoinNotify*) build;
- (RoomJoinNotify*) buildPartial;

- (RoomJoinNotifyBuilder*) mergeFrom:(RoomJoinNotify*) other;
- (RoomJoinNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomJoinNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomJoinNotifyBuilder*) setOwid:(SInt32) value;
- (RoomJoinNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (RoomJoinNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (RoomJoinNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (RoomJoinNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (RoomJoinNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (RoomJoinNotifyBuilder*) setUser:(User*) value;
- (RoomJoinNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (RoomJoinNotifyBuilder*) mergeUser:(User*) value;
- (RoomJoinNotifyBuilder*) clearUser;
@end

#define RoomLeaveReq_owid @"owid"
@interface RoomLeaveReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  SInt32 owid;
}
- (BOOL) hasOwid;
@property (readonly) SInt32 owid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomLeaveReqBuilder*) builder;
+ (RoomLeaveReqBuilder*) builder;
+ (RoomLeaveReqBuilder*) builderWithPrototype:(RoomLeaveReq*) prototype;
- (RoomLeaveReqBuilder*) toBuilder;

+ (RoomLeaveReq*) parseFromData:(NSData*) data;
+ (RoomLeaveReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomLeaveReq*) parseFromInputStream:(NSInputStream*) input;
+ (RoomLeaveReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomLeaveReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomLeaveReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomLeaveReqBuilder : PBGeneratedMessageBuilder {
@private
  RoomLeaveReq* resultRoomLeaveReq;
}

- (RoomLeaveReq*) defaultInstance;

- (RoomLeaveReqBuilder*) clear;
- (RoomLeaveReqBuilder*) clone;

- (RoomLeaveReq*) build;
- (RoomLeaveReq*) buildPartial;

- (RoomLeaveReqBuilder*) mergeFrom:(RoomLeaveReq*) other;
- (RoomLeaveReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomLeaveReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomLeaveReqBuilder*) setOwid:(SInt32) value;
- (RoomLeaveReqBuilder*) clearOwid;
@end

#define ChatUp_type @"type"
#define ChatUp_txt @"txt"
#define ChatUp_toUsers @"toUsers"
#define ChatUp_color @"color"
@interface ChatUp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasColor_:1;
  BOOL hasTxt_:1;
  SInt32 type;
  SInt32 color;
  NSString* txt;
  NSMutableArray * toUsersArray;
}
- (BOOL) hasType;
- (BOOL) hasTxt;
- (BOOL) hasColor;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* txt;
@property (readonly, strong) NSArray<User*> * toUsers;
@property (readonly) SInt32 color;
- (User*)toUsersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatUpBuilder*) builder;
+ (ChatUpBuilder*) builder;
+ (ChatUpBuilder*) builderWithPrototype:(ChatUp*) prototype;
- (ChatUpBuilder*) toBuilder;

+ (ChatUp*) parseFromData:(NSData*) data;
+ (ChatUp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatUp*) parseFromInputStream:(NSInputStream*) input;
+ (ChatUp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatUp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatUp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatUpBuilder : PBGeneratedMessageBuilder {
@private
  ChatUp* resultChatUp;
}

- (ChatUp*) defaultInstance;

- (ChatUpBuilder*) clear;
- (ChatUpBuilder*) clone;

- (ChatUp*) build;
- (ChatUp*) buildPartial;

- (ChatUpBuilder*) mergeFrom:(ChatUp*) other;
- (ChatUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (SInt32) type;
- (ChatUpBuilder*) setType:(SInt32) value;
- (ChatUpBuilder*) clearType;

- (BOOL) hasTxt;
- (NSString*) txt;
- (ChatUpBuilder*) setTxt:(NSString*) value;
- (ChatUpBuilder*) clearTxt;

- (NSMutableArray<User*> *)toUsers;
- (User*)toUsersAtIndex:(NSUInteger)index;
- (ChatUpBuilder *)addToUsers:(User*)value;
- (ChatUpBuilder *)setToUsersArray:(NSArray<User*> *)array;
- (ChatUpBuilder *)clearToUsers;

- (BOOL) hasColor;
- (SInt32) color;
- (ChatUpBuilder*) setColor:(SInt32) value;
- (ChatUpBuilder*) clearColor;
@end

#define ChatNotify_owid @"owid"
#define ChatNotify_roomAttr @"roomAttr"
#define ChatNotify_user @"user"
#define ChatNotify_type @"type"
#define ChatNotify_txt @"txt"
#define ChatNotify_color @"color"
#define ChatNotify_toUsers @"toUsers"
#define ChatNotify_retetionAttr @"retetionAttr"
@interface ChatNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasType_:1;
  BOOL hasColor_:1;
  BOOL hasTxt_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  BOOL hasRetetionAttr_:1;
  SInt32 owid;
  SInt32 type;
  SInt32 color;
  NSString* txt;
  RoomAttr* roomAttr;
  User* user;
  RetetionAttr* retetionAttr;
  NSMutableArray * toUsersArray;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasType;
- (BOOL) hasTxt;
- (BOOL) hasColor;
- (BOOL) hasRetetionAttr;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* txt;
@property (readonly) SInt32 color;
@property (readonly, strong) NSArray<User*> * toUsers;
@property (readonly, strong) RetetionAttr* retetionAttr;
- (User*)toUsersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatNotifyBuilder*) builder;
+ (ChatNotifyBuilder*) builder;
+ (ChatNotifyBuilder*) builderWithPrototype:(ChatNotify*) prototype;
- (ChatNotifyBuilder*) toBuilder;

+ (ChatNotify*) parseFromData:(NSData*) data;
+ (ChatNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatNotify*) parseFromInputStream:(NSInputStream*) input;
+ (ChatNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatNotifyBuilder : PBGeneratedMessageBuilder {
@private
  ChatNotify* resultChatNotify;
}

- (ChatNotify*) defaultInstance;

- (ChatNotifyBuilder*) clear;
- (ChatNotifyBuilder*) clone;

- (ChatNotify*) build;
- (ChatNotify*) buildPartial;

- (ChatNotifyBuilder*) mergeFrom:(ChatNotify*) other;
- (ChatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (ChatNotifyBuilder*) setOwid:(SInt32) value;
- (ChatNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (ChatNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (ChatNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (ChatNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (ChatNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (ChatNotifyBuilder*) setUser:(User*) value;
- (ChatNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (ChatNotifyBuilder*) mergeUser:(User*) value;
- (ChatNotifyBuilder*) clearUser;

- (BOOL) hasType;
- (SInt32) type;
- (ChatNotifyBuilder*) setType:(SInt32) value;
- (ChatNotifyBuilder*) clearType;

- (BOOL) hasTxt;
- (NSString*) txt;
- (ChatNotifyBuilder*) setTxt:(NSString*) value;
- (ChatNotifyBuilder*) clearTxt;

- (BOOL) hasColor;
- (SInt32) color;
- (ChatNotifyBuilder*) setColor:(SInt32) value;
- (ChatNotifyBuilder*) clearColor;

- (NSMutableArray<User*> *)toUsers;
- (User*)toUsersAtIndex:(NSUInteger)index;
- (ChatNotifyBuilder *)addToUsers:(User*)value;
- (ChatNotifyBuilder *)setToUsersArray:(NSArray<User*> *)array;
- (ChatNotifyBuilder *)clearToUsers;

- (BOOL) hasRetetionAttr;
- (RetetionAttr*) retetionAttr;
- (ChatNotifyBuilder*) setRetetionAttr:(RetetionAttr*) value;
- (ChatNotifyBuilder*) setRetetionAttrBuilder:(RetetionAttrBuilder*) builderForValue;
- (ChatNotifyBuilder*) mergeRetetionAttr:(RetetionAttr*) value;
- (ChatNotifyBuilder*) clearRetetionAttr;
@end

#define GiftUp_owid @"owid"
#define GiftUp_gid @"gid"
#define GiftUp_attrId @"attrId"
#define GiftUp_count @"count"
#define GiftUp_txt @"txt"
#define GiftUp_ext @"ext"
@interface GiftUp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasGid_:1;
  BOOL hasAttrId_:1;
  BOOL hasCount_:1;
  BOOL hasTxt_:1;
  BOOL hasExt_:1;
  SInt32 owid;
  SInt32 gid;
  SInt32 attrId;
  SInt32 count;
  NSString* txt;
  NSString* ext;
}
- (BOOL) hasOwid;
- (BOOL) hasGid;
- (BOOL) hasAttrId;
- (BOOL) hasCount;
- (BOOL) hasTxt;
- (BOOL) hasExt;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 gid;
@property (readonly) SInt32 attrId;
@property (readonly) SInt32 count;
@property (readonly, strong) NSString* txt;
@property (readonly, strong) NSString* ext;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GiftUpBuilder*) builder;
+ (GiftUpBuilder*) builder;
+ (GiftUpBuilder*) builderWithPrototype:(GiftUp*) prototype;
- (GiftUpBuilder*) toBuilder;

+ (GiftUp*) parseFromData:(NSData*) data;
+ (GiftUp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GiftUp*) parseFromInputStream:(NSInputStream*) input;
+ (GiftUp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GiftUp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GiftUp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GiftUpBuilder : PBGeneratedMessageBuilder {
@private
  GiftUp* resultGiftUp;
}

- (GiftUp*) defaultInstance;

- (GiftUpBuilder*) clear;
- (GiftUpBuilder*) clone;

- (GiftUp*) build;
- (GiftUp*) buildPartial;

- (GiftUpBuilder*) mergeFrom:(GiftUp*) other;
- (GiftUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GiftUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (GiftUpBuilder*) setOwid:(SInt32) value;
- (GiftUpBuilder*) clearOwid;

- (BOOL) hasGid;
- (SInt32) gid;
- (GiftUpBuilder*) setGid:(SInt32) value;
- (GiftUpBuilder*) clearGid;

- (BOOL) hasAttrId;
- (SInt32) attrId;
- (GiftUpBuilder*) setAttrId:(SInt32) value;
- (GiftUpBuilder*) clearAttrId;

- (BOOL) hasCount;
- (SInt32) count;
- (GiftUpBuilder*) setCount:(SInt32) value;
- (GiftUpBuilder*) clearCount;

- (BOOL) hasTxt;
- (NSString*) txt;
- (GiftUpBuilder*) setTxt:(NSString*) value;
- (GiftUpBuilder*) clearTxt;

- (BOOL) hasExt;
- (NSString*) ext;
- (GiftUpBuilder*) setExt:(NSString*) value;
- (GiftUpBuilder*) clearExt;
@end

#define GiftNotify_owid @"owid"
#define GiftNotify_roomAttr @"roomAttr"
#define GiftNotify_user @"user"
#define GiftNotify_combo @"combo"
#define GiftNotify_comboId @"comboId"
#define GiftNotify_gid @"gid"
#define GiftNotify_attrId @"attrId"
#define GiftNotify_count @"count"
#define GiftNotify_retetionAttr @"retetionAttr"
@interface GiftNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasCombo_:1;
  BOOL hasComboId_:1;
  BOOL hasGid_:1;
  BOOL hasAttrId_:1;
  BOOL hasCount_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  BOOL hasRetetionAttr_:1;
  SInt32 owid;
  SInt32 combo;
  SInt32 comboId;
  SInt32 gid;
  SInt32 attrId;
  SInt32 count;
  RoomAttr* roomAttr;
  User* user;
  RetetionAttr* retetionAttr;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasCombo;
- (BOOL) hasComboId;
- (BOOL) hasGid;
- (BOOL) hasAttrId;
- (BOOL) hasCount;
- (BOOL) hasRetetionAttr;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 combo;
@property (readonly) SInt32 comboId;
@property (readonly) SInt32 gid;
@property (readonly) SInt32 attrId;
@property (readonly) SInt32 count;
@property (readonly, strong) RetetionAttr* retetionAttr;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GiftNotifyBuilder*) builder;
+ (GiftNotifyBuilder*) builder;
+ (GiftNotifyBuilder*) builderWithPrototype:(GiftNotify*) prototype;
- (GiftNotifyBuilder*) toBuilder;

+ (GiftNotify*) parseFromData:(NSData*) data;
+ (GiftNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GiftNotify*) parseFromInputStream:(NSInputStream*) input;
+ (GiftNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GiftNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GiftNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GiftNotifyBuilder : PBGeneratedMessageBuilder {
@private
  GiftNotify* resultGiftNotify;
}

- (GiftNotify*) defaultInstance;

- (GiftNotifyBuilder*) clear;
- (GiftNotifyBuilder*) clone;

- (GiftNotify*) build;
- (GiftNotify*) buildPartial;

- (GiftNotifyBuilder*) mergeFrom:(GiftNotify*) other;
- (GiftNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GiftNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (GiftNotifyBuilder*) setOwid:(SInt32) value;
- (GiftNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (GiftNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (GiftNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (GiftNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (GiftNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (GiftNotifyBuilder*) setUser:(User*) value;
- (GiftNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (GiftNotifyBuilder*) mergeUser:(User*) value;
- (GiftNotifyBuilder*) clearUser;

- (BOOL) hasCombo;
- (SInt32) combo;
- (GiftNotifyBuilder*) setCombo:(SInt32) value;
- (GiftNotifyBuilder*) clearCombo;

- (BOOL) hasComboId;
- (SInt32) comboId;
- (GiftNotifyBuilder*) setComboId:(SInt32) value;
- (GiftNotifyBuilder*) clearComboId;

- (BOOL) hasGid;
- (SInt32) gid;
- (GiftNotifyBuilder*) setGid:(SInt32) value;
- (GiftNotifyBuilder*) clearGid;

- (BOOL) hasAttrId;
- (SInt32) attrId;
- (GiftNotifyBuilder*) setAttrId:(SInt32) value;
- (GiftNotifyBuilder*) clearAttrId;

- (BOOL) hasCount;
- (SInt32) count;
- (GiftNotifyBuilder*) setCount:(SInt32) value;
- (GiftNotifyBuilder*) clearCount;

- (BOOL) hasRetetionAttr;
- (RetetionAttr*) retetionAttr;
- (GiftNotifyBuilder*) setRetetionAttr:(RetetionAttr*) value;
- (GiftNotifyBuilder*) setRetetionAttrBuilder:(RetetionAttrBuilder*) builderForValue;
- (GiftNotifyBuilder*) mergeRetetionAttr:(RetetionAttr*) value;
- (GiftNotifyBuilder*) clearRetetionAttr;
@end

#define ZanUp_owid @"owid"
#define ZanUp_color @"color"
@interface ZanUp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasColor_:1;
  SInt32 owid;
  SInt32 color;
}
- (BOOL) hasOwid;
- (BOOL) hasColor;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 color;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ZanUpBuilder*) builder;
+ (ZanUpBuilder*) builder;
+ (ZanUpBuilder*) builderWithPrototype:(ZanUp*) prototype;
- (ZanUpBuilder*) toBuilder;

+ (ZanUp*) parseFromData:(NSData*) data;
+ (ZanUp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ZanUp*) parseFromInputStream:(NSInputStream*) input;
+ (ZanUp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ZanUp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ZanUp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ZanUpBuilder : PBGeneratedMessageBuilder {
@private
  ZanUp* resultZanUp;
}

- (ZanUp*) defaultInstance;

- (ZanUpBuilder*) clear;
- (ZanUpBuilder*) clone;

- (ZanUp*) build;
- (ZanUp*) buildPartial;

- (ZanUpBuilder*) mergeFrom:(ZanUp*) other;
- (ZanUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ZanUpBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (ZanUpBuilder*) setOwid:(SInt32) value;
- (ZanUpBuilder*) clearOwid;

- (BOOL) hasColor;
- (SInt32) color;
- (ZanUpBuilder*) setColor:(SInt32) value;
- (ZanUpBuilder*) clearColor;
@end

#define ZanNotify_owid @"owid"
#define ZanNotify_roomAttr @"roomAttr"
#define ZanNotify_user @"user"
#define ZanNotify_color @"color"
@interface ZanNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasColor_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  SInt32 color;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasColor;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 color;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ZanNotifyBuilder*) builder;
+ (ZanNotifyBuilder*) builder;
+ (ZanNotifyBuilder*) builderWithPrototype:(ZanNotify*) prototype;
- (ZanNotifyBuilder*) toBuilder;

+ (ZanNotify*) parseFromData:(NSData*) data;
+ (ZanNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ZanNotify*) parseFromInputStream:(NSInputStream*) input;
+ (ZanNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ZanNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ZanNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ZanNotifyBuilder : PBGeneratedMessageBuilder {
@private
  ZanNotify* resultZanNotify;
}

- (ZanNotify*) defaultInstance;

- (ZanNotifyBuilder*) clear;
- (ZanNotifyBuilder*) clone;

- (ZanNotify*) build;
- (ZanNotify*) buildPartial;

- (ZanNotifyBuilder*) mergeFrom:(ZanNotify*) other;
- (ZanNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ZanNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (ZanNotifyBuilder*) setOwid:(SInt32) value;
- (ZanNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (ZanNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (ZanNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (ZanNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (ZanNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (ZanNotifyBuilder*) setUser:(User*) value;
- (ZanNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (ZanNotifyBuilder*) mergeUser:(User*) value;
- (ZanNotifyBuilder*) clearUser;

- (BOOL) hasColor;
- (SInt32) color;
- (ZanNotifyBuilder*) setColor:(SInt32) value;
- (ZanNotifyBuilder*) clearColor;
@end

#define ManagerNotify_owid @"owid"
#define ManagerNotify_roomAttr @"roomAttr"
#define ManagerNotify_user @"user"
#define ManagerNotify_status @"status"
@interface ManagerNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasStatus_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  SInt32 status;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasStatus;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ManagerNotifyBuilder*) builder;
+ (ManagerNotifyBuilder*) builder;
+ (ManagerNotifyBuilder*) builderWithPrototype:(ManagerNotify*) prototype;
- (ManagerNotifyBuilder*) toBuilder;

+ (ManagerNotify*) parseFromData:(NSData*) data;
+ (ManagerNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ManagerNotify*) parseFromInputStream:(NSInputStream*) input;
+ (ManagerNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ManagerNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ManagerNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ManagerNotifyBuilder : PBGeneratedMessageBuilder {
@private
  ManagerNotify* resultManagerNotify;
}

- (ManagerNotify*) defaultInstance;

- (ManagerNotifyBuilder*) clear;
- (ManagerNotifyBuilder*) clone;

- (ManagerNotify*) build;
- (ManagerNotify*) buildPartial;

- (ManagerNotifyBuilder*) mergeFrom:(ManagerNotify*) other;
- (ManagerNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ManagerNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (ManagerNotifyBuilder*) setOwid:(SInt32) value;
- (ManagerNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (ManagerNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (ManagerNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (ManagerNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (ManagerNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (ManagerNotifyBuilder*) setUser:(User*) value;
- (ManagerNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (ManagerNotifyBuilder*) mergeUser:(User*) value;
- (ManagerNotifyBuilder*) clearUser;

- (BOOL) hasStatus;
- (SInt32) status;
- (ManagerNotifyBuilder*) setStatus:(SInt32) value;
- (ManagerNotifyBuilder*) clearStatus;
@end

#define RoomUpdateNotify_owid @"owid"
#define RoomUpdateNotify_liveData @"liveData"
@interface RoomUpdateNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasLiveData_:1;
  SInt32 owid;
  LiveData* liveData;
}
- (BOOL) hasOwid;
- (BOOL) hasLiveData;
@property (readonly) SInt32 owid;
@property (readonly, strong) LiveData* liveData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomUpdateNotifyBuilder*) builder;
+ (RoomUpdateNotifyBuilder*) builder;
+ (RoomUpdateNotifyBuilder*) builderWithPrototype:(RoomUpdateNotify*) prototype;
- (RoomUpdateNotifyBuilder*) toBuilder;

+ (RoomUpdateNotify*) parseFromData:(NSData*) data;
+ (RoomUpdateNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomUpdateNotify*) parseFromInputStream:(NSInputStream*) input;
+ (RoomUpdateNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomUpdateNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomUpdateNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomUpdateNotifyBuilder : PBGeneratedMessageBuilder {
@private
  RoomUpdateNotify* resultRoomUpdateNotify;
}

- (RoomUpdateNotify*) defaultInstance;

- (RoomUpdateNotifyBuilder*) clear;
- (RoomUpdateNotifyBuilder*) clone;

- (RoomUpdateNotify*) build;
- (RoomUpdateNotify*) buildPartial;

- (RoomUpdateNotifyBuilder*) mergeFrom:(RoomUpdateNotify*) other;
- (RoomUpdateNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomUpdateNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RoomUpdateNotifyBuilder*) setOwid:(SInt32) value;
- (RoomUpdateNotifyBuilder*) clearOwid;

- (BOOL) hasLiveData;
- (LiveData*) liveData;
- (RoomUpdateNotifyBuilder*) setLiveData:(LiveData*) value;
- (RoomUpdateNotifyBuilder*) setLiveDataBuilder:(LiveDataBuilder*) builderForValue;
- (RoomUpdateNotifyBuilder*) mergeLiveData:(LiveData*) value;
- (RoomUpdateNotifyBuilder*) clearLiveData;
@end

#define AnchorLiveStatusNotify_owid @"owid"
#define AnchorLiveStatusNotify_type @"type"
@interface AnchorLiveStatusNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasType_:1;
  SInt32 owid;
  SInt32 type;
}
- (BOOL) hasOwid;
- (BOOL) hasType;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnchorLiveStatusNotifyBuilder*) builder;
+ (AnchorLiveStatusNotifyBuilder*) builder;
+ (AnchorLiveStatusNotifyBuilder*) builderWithPrototype:(AnchorLiveStatusNotify*) prototype;
- (AnchorLiveStatusNotifyBuilder*) toBuilder;

+ (AnchorLiveStatusNotify*) parseFromData:(NSData*) data;
+ (AnchorLiveStatusNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnchorLiveStatusNotify*) parseFromInputStream:(NSInputStream*) input;
+ (AnchorLiveStatusNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnchorLiveStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AnchorLiveStatusNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnchorLiveStatusNotifyBuilder : PBGeneratedMessageBuilder {
@private
  AnchorLiveStatusNotify* resultAnchorLiveStatusNotify;
}

- (AnchorLiveStatusNotify*) defaultInstance;

- (AnchorLiveStatusNotifyBuilder*) clear;
- (AnchorLiveStatusNotifyBuilder*) clone;

- (AnchorLiveStatusNotify*) build;
- (AnchorLiveStatusNotify*) buildPartial;

- (AnchorLiveStatusNotifyBuilder*) mergeFrom:(AnchorLiveStatusNotify*) other;
- (AnchorLiveStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnchorLiveStatusNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (AnchorLiveStatusNotifyBuilder*) setOwid:(SInt32) value;
- (AnchorLiveStatusNotifyBuilder*) clearOwid;

- (BOOL) hasType;
- (SInt32) type;
- (AnchorLiveStatusNotifyBuilder*) setType:(SInt32) value;
- (AnchorLiveStatusNotifyBuilder*) clearType;
@end

#define SharedNotify_owid @"owid"
#define SharedNotify_roomAttr @"roomAttr"
#define SharedNotify_user @"user"
#define SharedNotify_type @"type"
#define SharedNotify_tips @"tips"
@interface SharedNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasType_:1;
  BOOL hasTips_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  NSString* type;
  NSString* tips;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasType;
- (BOOL) hasTips;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly, strong) NSString* type;
@property (readonly, strong) NSString* tips;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SharedNotifyBuilder*) builder;
+ (SharedNotifyBuilder*) builder;
+ (SharedNotifyBuilder*) builderWithPrototype:(SharedNotify*) prototype;
- (SharedNotifyBuilder*) toBuilder;

+ (SharedNotify*) parseFromData:(NSData*) data;
+ (SharedNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SharedNotify*) parseFromInputStream:(NSInputStream*) input;
+ (SharedNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SharedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SharedNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SharedNotifyBuilder : PBGeneratedMessageBuilder {
@private
  SharedNotify* resultSharedNotify;
}

- (SharedNotify*) defaultInstance;

- (SharedNotifyBuilder*) clear;
- (SharedNotifyBuilder*) clone;

- (SharedNotify*) build;
- (SharedNotify*) buildPartial;

- (SharedNotifyBuilder*) mergeFrom:(SharedNotify*) other;
- (SharedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SharedNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (SharedNotifyBuilder*) setOwid:(SInt32) value;
- (SharedNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (SharedNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (SharedNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (SharedNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (SharedNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (SharedNotifyBuilder*) setUser:(User*) value;
- (SharedNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (SharedNotifyBuilder*) mergeUser:(User*) value;
- (SharedNotifyBuilder*) clearUser;

- (BOOL) hasType;
- (NSString*) type;
- (SharedNotifyBuilder*) setType:(NSString*) value;
- (SharedNotifyBuilder*) clearType;

- (BOOL) hasTips;
- (NSString*) tips;
- (SharedNotifyBuilder*) setTips:(NSString*) value;
- (SharedNotifyBuilder*) clearTips;
@end

#define FollowNotify_owid @"owid"
#define FollowNotify_roomAttr @"roomAttr"
#define FollowNotify_user @"user"
#define FollowNotify_tips @"tips"
@interface FollowNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasTips_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  NSString* tips;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasTips;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly, strong) NSString* tips;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FollowNotifyBuilder*) builder;
+ (FollowNotifyBuilder*) builder;
+ (FollowNotifyBuilder*) builderWithPrototype:(FollowNotify*) prototype;
- (FollowNotifyBuilder*) toBuilder;

+ (FollowNotify*) parseFromData:(NSData*) data;
+ (FollowNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FollowNotify*) parseFromInputStream:(NSInputStream*) input;
+ (FollowNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FollowNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FollowNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FollowNotifyBuilder : PBGeneratedMessageBuilder {
@private
  FollowNotify* resultFollowNotify;
}

- (FollowNotify*) defaultInstance;

- (FollowNotifyBuilder*) clear;
- (FollowNotifyBuilder*) clone;

- (FollowNotify*) build;
- (FollowNotify*) buildPartial;

- (FollowNotifyBuilder*) mergeFrom:(FollowNotify*) other;
- (FollowNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FollowNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (FollowNotifyBuilder*) setOwid:(SInt32) value;
- (FollowNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (FollowNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (FollowNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (FollowNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (FollowNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (FollowNotifyBuilder*) setUser:(User*) value;
- (FollowNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (FollowNotifyBuilder*) mergeUser:(User*) value;
- (FollowNotifyBuilder*) clearUser;

- (BOOL) hasTips;
- (NSString*) tips;
- (FollowNotifyBuilder*) setTips:(NSString*) value;
- (FollowNotifyBuilder*) clearTips;
@end

#define RedEnvelopeNotify_owid @"owid"
#define RedEnvelopeNotify_roomAttr @"roomAttr"
#define RedEnvelopeNotify_user @"user"
#define RedEnvelopeNotify_rid @"rid"
#define RedEnvelopeNotify_type @"type"
#define RedEnvelopeNotify_amount @"amount"
#define RedEnvelopeNotify_txt @"txt"
#define RedEnvelopeNotify_retetionAttr @"retetionAttr"
#define RedEnvelopeNotify_key @"key"
@interface RedEnvelopeNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasRid_:1;
  BOOL hasType_:1;
  BOOL hasAmount_:1;
  BOOL hasTxt_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  BOOL hasRetetionAttr_:1;
  BOOL hasKey_:1;
  SInt32 owid;
  SInt32 rid;
  SInt32 type;
  SInt32 amount;
  NSString* txt;
  RoomAttr* roomAttr;
  User* user;
  RetetionAttr* retetionAttr;
  UInt32 key;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasRid;
- (BOOL) hasType;
- (BOOL) hasAmount;
- (BOOL) hasTxt;
- (BOOL) hasRetetionAttr;
- (BOOL) hasKey;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 rid;
@property (readonly) SInt32 type;
@property (readonly) SInt32 amount;
@property (readonly, strong) NSString* txt;
@property (readonly, strong) RetetionAttr* retetionAttr;
@property (readonly) UInt32 key;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RedEnvelopeNotifyBuilder*) builder;
+ (RedEnvelopeNotifyBuilder*) builder;
+ (RedEnvelopeNotifyBuilder*) builderWithPrototype:(RedEnvelopeNotify*) prototype;
- (RedEnvelopeNotifyBuilder*) toBuilder;

+ (RedEnvelopeNotify*) parseFromData:(NSData*) data;
+ (RedEnvelopeNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RedEnvelopeNotify*) parseFromInputStream:(NSInputStream*) input;
+ (RedEnvelopeNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RedEnvelopeNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RedEnvelopeNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RedEnvelopeNotifyBuilder : PBGeneratedMessageBuilder {
@private
  RedEnvelopeNotify* resultRedEnvelopeNotify;
}

- (RedEnvelopeNotify*) defaultInstance;

- (RedEnvelopeNotifyBuilder*) clear;
- (RedEnvelopeNotifyBuilder*) clone;

- (RedEnvelopeNotify*) build;
- (RedEnvelopeNotify*) buildPartial;

- (RedEnvelopeNotifyBuilder*) mergeFrom:(RedEnvelopeNotify*) other;
- (RedEnvelopeNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RedEnvelopeNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (RedEnvelopeNotifyBuilder*) setOwid:(SInt32) value;
- (RedEnvelopeNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (RedEnvelopeNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (RedEnvelopeNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (RedEnvelopeNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (RedEnvelopeNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (RedEnvelopeNotifyBuilder*) setUser:(User*) value;
- (RedEnvelopeNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (RedEnvelopeNotifyBuilder*) mergeUser:(User*) value;
- (RedEnvelopeNotifyBuilder*) clearUser;

- (BOOL) hasRid;
- (SInt32) rid;
- (RedEnvelopeNotifyBuilder*) setRid:(SInt32) value;
- (RedEnvelopeNotifyBuilder*) clearRid;

- (BOOL) hasType;
- (SInt32) type;
- (RedEnvelopeNotifyBuilder*) setType:(SInt32) value;
- (RedEnvelopeNotifyBuilder*) clearType;

- (BOOL) hasAmount;
- (SInt32) amount;
- (RedEnvelopeNotifyBuilder*) setAmount:(SInt32) value;
- (RedEnvelopeNotifyBuilder*) clearAmount;

- (BOOL) hasTxt;
- (NSString*) txt;
- (RedEnvelopeNotifyBuilder*) setTxt:(NSString*) value;
- (RedEnvelopeNotifyBuilder*) clearTxt;

- (BOOL) hasRetetionAttr;
- (RetetionAttr*) retetionAttr;
- (RedEnvelopeNotifyBuilder*) setRetetionAttr:(RetetionAttr*) value;
- (RedEnvelopeNotifyBuilder*) setRetetionAttrBuilder:(RetetionAttrBuilder*) builderForValue;
- (RedEnvelopeNotifyBuilder*) mergeRetetionAttr:(RetetionAttr*) value;
- (RedEnvelopeNotifyBuilder*) clearRetetionAttr;

- (BOOL) hasKey;
- (UInt32) key;
- (RedEnvelopeNotifyBuilder*) setKey:(UInt32) value;
- (RedEnvelopeNotifyBuilder*) clearKey;
@end

#define UserAttrNotify_user @"user"
#define UserAttrNotify_diamond @"diamond"
#define UserAttrNotify_starlight @"starlight"
#define UserAttrNotify_fight @"fight"
#define UserAttrNotify_seed @"seed"
@interface UserAttrNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDiamond_:1;
  BOOL hasStarlight_:1;
  BOOL hasFight_:1;
  BOOL hasSeed_:1;
  BOOL hasUser_:1;
  SInt32 diamond;
  SInt32 starlight;
  SInt32 fight;
  SInt32 seed;
  User* user;
}
- (BOOL) hasUser;
- (BOOL) hasDiamond;
- (BOOL) hasStarlight;
- (BOOL) hasFight;
- (BOOL) hasSeed;
@property (readonly, strong) User* user;
@property (readonly) SInt32 diamond;
@property (readonly) SInt32 starlight;
@property (readonly) SInt32 fight;
@property (readonly) SInt32 seed;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserAttrNotifyBuilder*) builder;
+ (UserAttrNotifyBuilder*) builder;
+ (UserAttrNotifyBuilder*) builderWithPrototype:(UserAttrNotify*) prototype;
- (UserAttrNotifyBuilder*) toBuilder;

+ (UserAttrNotify*) parseFromData:(NSData*) data;
+ (UserAttrNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttrNotify*) parseFromInputStream:(NSInputStream*) input;
+ (UserAttrNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttrNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserAttrNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserAttrNotifyBuilder : PBGeneratedMessageBuilder {
@private
  UserAttrNotify* resultUserAttrNotify;
}

- (UserAttrNotify*) defaultInstance;

- (UserAttrNotifyBuilder*) clear;
- (UserAttrNotifyBuilder*) clone;

- (UserAttrNotify*) build;
- (UserAttrNotify*) buildPartial;

- (UserAttrNotifyBuilder*) mergeFrom:(UserAttrNotify*) other;
- (UserAttrNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserAttrNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (User*) user;
- (UserAttrNotifyBuilder*) setUser:(User*) value;
- (UserAttrNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (UserAttrNotifyBuilder*) mergeUser:(User*) value;
- (UserAttrNotifyBuilder*) clearUser;

- (BOOL) hasDiamond;
- (SInt32) diamond;
- (UserAttrNotifyBuilder*) setDiamond:(SInt32) value;
- (UserAttrNotifyBuilder*) clearDiamond;

- (BOOL) hasStarlight;
- (SInt32) starlight;
- (UserAttrNotifyBuilder*) setStarlight:(SInt32) value;
- (UserAttrNotifyBuilder*) clearStarlight;

- (BOOL) hasFight;
- (SInt32) fight;
- (UserAttrNotifyBuilder*) setFight:(SInt32) value;
- (UserAttrNotifyBuilder*) clearFight;

- (BOOL) hasSeed;
- (SInt32) seed;
- (UserAttrNotifyBuilder*) setSeed:(SInt32) value;
- (UserAttrNotifyBuilder*) clearSeed;
@end

#define UserLevelUpNotify_owid @"owid"
#define UserLevelUpNotify_roomAttr @"roomAttr"
#define UserLevelUpNotify_user @"user"
#define UserLevelUpNotify_nextLevel @"nextLevel"
#define UserLevelUpNotify_needDiamod @"needDiamod"
#define UserLevelUpNotify_percent @"percent"
#define UserLevelUpNotify_type @"type"
#define UserLevelUpNotify_tips @"tips"
@interface UserLevelUpNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasNextLevel_:1;
  BOOL hasNeedDiamod_:1;
  BOOL hasPercent_:1;
  BOOL hasType_:1;
  BOOL hasTips_:1;
  BOOL hasRoomAttr_:1;
  BOOL hasUser_:1;
  SInt32 owid;
  SInt32 nextLevel;
  SInt32 needDiamod;
  SInt32 percent;
  SInt32 type;
  NSString* tips;
  RoomAttr* roomAttr;
  User* user;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomAttr;
- (BOOL) hasUser;
- (BOOL) hasNextLevel;
- (BOOL) hasNeedDiamod;
- (BOOL) hasPercent;
- (BOOL) hasType;
- (BOOL) hasTips;
@property (readonly) SInt32 owid;
@property (readonly, strong) RoomAttr* roomAttr;
@property (readonly, strong) User* user;
@property (readonly) SInt32 nextLevel;
@property (readonly) SInt32 needDiamod;
@property (readonly) SInt32 percent;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* tips;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserLevelUpNotifyBuilder*) builder;
+ (UserLevelUpNotifyBuilder*) builder;
+ (UserLevelUpNotifyBuilder*) builderWithPrototype:(UserLevelUpNotify*) prototype;
- (UserLevelUpNotifyBuilder*) toBuilder;

+ (UserLevelUpNotify*) parseFromData:(NSData*) data;
+ (UserLevelUpNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLevelUpNotify*) parseFromInputStream:(NSInputStream*) input;
+ (UserLevelUpNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLevelUpNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserLevelUpNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserLevelUpNotifyBuilder : PBGeneratedMessageBuilder {
@private
  UserLevelUpNotify* resultUserLevelUpNotify;
}

- (UserLevelUpNotify*) defaultInstance;

- (UserLevelUpNotifyBuilder*) clear;
- (UserLevelUpNotifyBuilder*) clone;

- (UserLevelUpNotify*) build;
- (UserLevelUpNotify*) buildPartial;

- (UserLevelUpNotifyBuilder*) mergeFrom:(UserLevelUpNotify*) other;
- (UserLevelUpNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserLevelUpNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (UserLevelUpNotifyBuilder*) setOwid:(SInt32) value;
- (UserLevelUpNotifyBuilder*) clearOwid;

- (BOOL) hasRoomAttr;
- (RoomAttr*) roomAttr;
- (UserLevelUpNotifyBuilder*) setRoomAttr:(RoomAttr*) value;
- (UserLevelUpNotifyBuilder*) setRoomAttrBuilder:(RoomAttrBuilder*) builderForValue;
- (UserLevelUpNotifyBuilder*) mergeRoomAttr:(RoomAttr*) value;
- (UserLevelUpNotifyBuilder*) clearRoomAttr;

- (BOOL) hasUser;
- (User*) user;
- (UserLevelUpNotifyBuilder*) setUser:(User*) value;
- (UserLevelUpNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (UserLevelUpNotifyBuilder*) mergeUser:(User*) value;
- (UserLevelUpNotifyBuilder*) clearUser;

- (BOOL) hasNextLevel;
- (SInt32) nextLevel;
- (UserLevelUpNotifyBuilder*) setNextLevel:(SInt32) value;
- (UserLevelUpNotifyBuilder*) clearNextLevel;

- (BOOL) hasNeedDiamod;
- (SInt32) needDiamod;
- (UserLevelUpNotifyBuilder*) setNeedDiamod:(SInt32) value;
- (UserLevelUpNotifyBuilder*) clearNeedDiamod;

- (BOOL) hasPercent;
- (SInt32) percent;
- (UserLevelUpNotifyBuilder*) setPercent:(SInt32) value;
- (UserLevelUpNotifyBuilder*) clearPercent;

- (BOOL) hasType;
- (SInt32) type;
- (UserLevelUpNotifyBuilder*) setType:(SInt32) value;
- (UserLevelUpNotifyBuilder*) clearType;

- (BOOL) hasTips;
- (NSString*) tips;
- (UserLevelUpNotifyBuilder*) setTips:(NSString*) value;
- (UserLevelUpNotifyBuilder*) clearTips;
@end

#define KickoutNotify_owid @"owid"
#define KickoutNotify_msg @"msg"
@interface KickoutNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasMsg_:1;
  SInt32 owid;
  NSString* msg;
}
- (BOOL) hasOwid;
- (BOOL) hasMsg;
@property (readonly) SInt32 owid;
@property (readonly, strong) NSString* msg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (KickoutNotifyBuilder*) builder;
+ (KickoutNotifyBuilder*) builder;
+ (KickoutNotifyBuilder*) builderWithPrototype:(KickoutNotify*) prototype;
- (KickoutNotifyBuilder*) toBuilder;

+ (KickoutNotify*) parseFromData:(NSData*) data;
+ (KickoutNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KickoutNotify*) parseFromInputStream:(NSInputStream*) input;
+ (KickoutNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KickoutNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (KickoutNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface KickoutNotifyBuilder : PBGeneratedMessageBuilder {
@private
  KickoutNotify* resultKickoutNotify;
}

- (KickoutNotify*) defaultInstance;

- (KickoutNotifyBuilder*) clear;
- (KickoutNotifyBuilder*) clone;

- (KickoutNotify*) build;
- (KickoutNotify*) buildPartial;

- (KickoutNotifyBuilder*) mergeFrom:(KickoutNotify*) other;
- (KickoutNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (KickoutNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (KickoutNotifyBuilder*) setOwid:(SInt32) value;
- (KickoutNotifyBuilder*) clearOwid;

- (BOOL) hasMsg;
- (NSString*) msg;
- (KickoutNotifyBuilder*) setMsg:(NSString*) value;
- (KickoutNotifyBuilder*) clearMsg;
@end

#define LinkApply_owid @"owid"
#define LinkApply_uid @"uid"
#define LinkApply_applyCount @"applyCount"
@interface LinkApply : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasUid_:1;
  BOOL hasApplyCount_:1;
  SInt32 owid;
  SInt32 uid;
  SInt32 applyCount;
}
- (BOOL) hasOwid;
- (BOOL) hasUid;
- (BOOL) hasApplyCount;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 uid;
@property (readonly) SInt32 applyCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkApplyBuilder*) builder;
+ (LinkApplyBuilder*) builder;
+ (LinkApplyBuilder*) builderWithPrototype:(LinkApply*) prototype;
- (LinkApplyBuilder*) toBuilder;

+ (LinkApply*) parseFromData:(NSData*) data;
+ (LinkApply*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkApply*) parseFromInputStream:(NSInputStream*) input;
+ (LinkApply*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkApply*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkApply*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkApplyBuilder : PBGeneratedMessageBuilder {
@private
  LinkApply* resultLinkApply;
}

- (LinkApply*) defaultInstance;

- (LinkApplyBuilder*) clear;
- (LinkApplyBuilder*) clone;

- (LinkApply*) build;
- (LinkApply*) buildPartial;

- (LinkApplyBuilder*) mergeFrom:(LinkApply*) other;
- (LinkApplyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkApplyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkApplyBuilder*) setOwid:(SInt32) value;
- (LinkApplyBuilder*) clearOwid;

- (BOOL) hasUid;
- (SInt32) uid;
- (LinkApplyBuilder*) setUid:(SInt32) value;
- (LinkApplyBuilder*) clearUid;

- (BOOL) hasApplyCount;
- (SInt32) applyCount;
- (LinkApplyBuilder*) setApplyCount:(SInt32) value;
- (LinkApplyBuilder*) clearApplyCount;
@end

#define LinkCancel_owid @"owid"
#define LinkCancel_uid @"uid"
#define LinkCancel_applyCount @"applyCount"
@interface LinkCancel : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasUid_:1;
  BOOL hasApplyCount_:1;
  SInt32 owid;
  SInt32 uid;
  SInt32 applyCount;
}
- (BOOL) hasOwid;
- (BOOL) hasUid;
- (BOOL) hasApplyCount;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 uid;
@property (readonly) SInt32 applyCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkCancelBuilder*) builder;
+ (LinkCancelBuilder*) builder;
+ (LinkCancelBuilder*) builderWithPrototype:(LinkCancel*) prototype;
- (LinkCancelBuilder*) toBuilder;

+ (LinkCancel*) parseFromData:(NSData*) data;
+ (LinkCancel*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkCancel*) parseFromInputStream:(NSInputStream*) input;
+ (LinkCancel*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkCancel*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkCancel*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkCancelBuilder : PBGeneratedMessageBuilder {
@private
  LinkCancel* resultLinkCancel;
}

- (LinkCancel*) defaultInstance;

- (LinkCancelBuilder*) clear;
- (LinkCancelBuilder*) clone;

- (LinkCancel*) build;
- (LinkCancel*) buildPartial;

- (LinkCancelBuilder*) mergeFrom:(LinkCancel*) other;
- (LinkCancelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkCancelBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkCancelBuilder*) setOwid:(SInt32) value;
- (LinkCancelBuilder*) clearOwid;

- (BOOL) hasUid;
- (SInt32) uid;
- (LinkCancelBuilder*) setUid:(SInt32) value;
- (LinkCancelBuilder*) clearUid;

- (BOOL) hasApplyCount;
- (SInt32) applyCount;
- (LinkCancelBuilder*) setApplyCount:(SInt32) value;
- (LinkCancelBuilder*) clearApplyCount;
@end

#define LinkClose_owid @"owid"
#define LinkClose_applyCount @"applyCount"
@interface LinkClose : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasApplyCount_:1;
  SInt32 owid;
  SInt32 applyCount;
}
- (BOOL) hasOwid;
- (BOOL) hasApplyCount;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 applyCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkCloseBuilder*) builder;
+ (LinkCloseBuilder*) builder;
+ (LinkCloseBuilder*) builderWithPrototype:(LinkClose*) prototype;
- (LinkCloseBuilder*) toBuilder;

+ (LinkClose*) parseFromData:(NSData*) data;
+ (LinkClose*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkClose*) parseFromInputStream:(NSInputStream*) input;
+ (LinkClose*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkClose*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkClose*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkCloseBuilder : PBGeneratedMessageBuilder {
@private
  LinkClose* resultLinkClose;
}

- (LinkClose*) defaultInstance;

- (LinkCloseBuilder*) clear;
- (LinkCloseBuilder*) clone;

- (LinkClose*) build;
- (LinkClose*) buildPartial;

- (LinkCloseBuilder*) mergeFrom:(LinkClose*) other;
- (LinkCloseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkCloseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkCloseBuilder*) setOwid:(SInt32) value;
- (LinkCloseBuilder*) clearOwid;

- (BOOL) hasApplyCount;
- (SInt32) applyCount;
- (LinkCloseBuilder*) setApplyCount:(SInt32) value;
- (LinkCloseBuilder*) clearApplyCount;
@end

#define LinkApplyCountChg_owid @"owid"
#define LinkApplyCountChg_applyCount @"applyCount"
@interface LinkApplyCountChg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasApplyCount_:1;
  SInt32 owid;
  SInt32 applyCount;
}
- (BOOL) hasOwid;
- (BOOL) hasApplyCount;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 applyCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkApplyCountChgBuilder*) builder;
+ (LinkApplyCountChgBuilder*) builder;
+ (LinkApplyCountChgBuilder*) builderWithPrototype:(LinkApplyCountChg*) prototype;
- (LinkApplyCountChgBuilder*) toBuilder;

+ (LinkApplyCountChg*) parseFromData:(NSData*) data;
+ (LinkApplyCountChg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkApplyCountChg*) parseFromInputStream:(NSInputStream*) input;
+ (LinkApplyCountChg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkApplyCountChg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkApplyCountChg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkApplyCountChgBuilder : PBGeneratedMessageBuilder {
@private
  LinkApplyCountChg* resultLinkApplyCountChg;
}

- (LinkApplyCountChg*) defaultInstance;

- (LinkApplyCountChgBuilder*) clear;
- (LinkApplyCountChgBuilder*) clone;

- (LinkApplyCountChg*) build;
- (LinkApplyCountChg*) buildPartial;

- (LinkApplyCountChgBuilder*) mergeFrom:(LinkApplyCountChg*) other;
- (LinkApplyCountChgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkApplyCountChgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkApplyCountChgBuilder*) setOwid:(SInt32) value;
- (LinkApplyCountChgBuilder*) clearOwid;

- (BOOL) hasApplyCount;
- (SInt32) applyCount;
- (LinkApplyCountChgBuilder*) setApplyCount:(SInt32) value;
- (LinkApplyCountChgBuilder*) clearApplyCount;
@end

#define LinkAccept_owid @"owid"
#define LinkAccept_roomName @"roomName"
#define LinkAccept_token @"token"
@interface LinkAccept : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasRoomName_:1;
  BOOL hasToken_:1;
  SInt32 owid;
  NSString* roomName;
  NSString* token;
}
- (BOOL) hasOwid;
- (BOOL) hasRoomName;
- (BOOL) hasToken;
@property (readonly) SInt32 owid;
@property (readonly, strong) NSString* roomName;
@property (readonly, strong) NSString* token;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkAcceptBuilder*) builder;
+ (LinkAcceptBuilder*) builder;
+ (LinkAcceptBuilder*) builderWithPrototype:(LinkAccept*) prototype;
- (LinkAcceptBuilder*) toBuilder;

+ (LinkAccept*) parseFromData:(NSData*) data;
+ (LinkAccept*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkAccept*) parseFromInputStream:(NSInputStream*) input;
+ (LinkAccept*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkAccept*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkAccept*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkAcceptBuilder : PBGeneratedMessageBuilder {
@private
  LinkAccept* resultLinkAccept;
}

- (LinkAccept*) defaultInstance;

- (LinkAcceptBuilder*) clear;
- (LinkAcceptBuilder*) clone;

- (LinkAccept*) build;
- (LinkAccept*) buildPartial;

- (LinkAcceptBuilder*) mergeFrom:(LinkAccept*) other;
- (LinkAcceptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkAcceptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkAcceptBuilder*) setOwid:(SInt32) value;
- (LinkAcceptBuilder*) clearOwid;

- (BOOL) hasRoomName;
- (NSString*) roomName;
- (LinkAcceptBuilder*) setRoomName:(NSString*) value;
- (LinkAcceptBuilder*) clearRoomName;

- (BOOL) hasToken;
- (NSString*) token;
- (LinkAcceptBuilder*) setToken:(NSString*) value;
- (LinkAcceptBuilder*) clearToken;
@end

#define LinkBroadcast_owid @"owid"
#define LinkBroadcast_status @"status"
#define LinkBroadcast_linkers @"linkers"
@interface LinkBroadcast : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasStatus_:1;
  SInt32 owid;
  SInt32 status;
  NSMutableArray * linkersArray;
}
- (BOOL) hasOwid;
- (BOOL) hasStatus;
@property (readonly) SInt32 owid;
@property (readonly) SInt32 status;
@property (readonly, strong) NSArray<User*> * linkers;
- (User*)linkersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LinkBroadcastBuilder*) builder;
+ (LinkBroadcastBuilder*) builder;
+ (LinkBroadcastBuilder*) builderWithPrototype:(LinkBroadcast*) prototype;
- (LinkBroadcastBuilder*) toBuilder;

+ (LinkBroadcast*) parseFromData:(NSData*) data;
+ (LinkBroadcast*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkBroadcast*) parseFromInputStream:(NSInputStream*) input;
+ (LinkBroadcast*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LinkBroadcast*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LinkBroadcast*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LinkBroadcastBuilder : PBGeneratedMessageBuilder {
@private
  LinkBroadcast* resultLinkBroadcast;
}

- (LinkBroadcast*) defaultInstance;

- (LinkBroadcastBuilder*) clear;
- (LinkBroadcastBuilder*) clone;

- (LinkBroadcast*) build;
- (LinkBroadcast*) buildPartial;

- (LinkBroadcastBuilder*) mergeFrom:(LinkBroadcast*) other;
- (LinkBroadcastBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LinkBroadcastBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (LinkBroadcastBuilder*) setOwid:(SInt32) value;
- (LinkBroadcastBuilder*) clearOwid;

- (BOOL) hasStatus;
- (SInt32) status;
- (LinkBroadcastBuilder*) setStatus:(SInt32) value;
- (LinkBroadcastBuilder*) clearStatus;

- (NSMutableArray<User*> *)linkers;
- (User*)linkersAtIndex:(NSUInteger)index;
- (LinkBroadcastBuilder *)addLinkers:(User*)value;
- (LinkBroadcastBuilder *)setLinkersArray:(NSArray<User*> *)array;
- (LinkBroadcastBuilder *)clearLinkers;
@end

#define BannerNotify_owid @"owid"
#define BannerNotify_user @"user"
#define BannerNotify_anchor @"anchor"
#define BannerNotify_templateId @"templateId"
#define BannerNotify_gid @"gid"
#define BannerNotify_attrId @"attrId"
#define BannerNotify_giftCount @"giftCount"
@interface BannerNotify : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOwid_:1;
  BOOL hasTemplateId_:1;
  BOOL hasGid_:1;
  BOOL hasAttrId_:1;
  BOOL hasGiftCount_:1;
  BOOL hasUser_:1;
  BOOL hasAnchor_:1;
  SInt32 owid;
  SInt32 templateId;
  SInt32 gid;
  SInt32 attrId;
  SInt32 giftCount;
  User* user;
  User* anchor;
}
- (BOOL) hasOwid;
- (BOOL) hasUser;
- (BOOL) hasAnchor;
- (BOOL) hasTemplateId;
- (BOOL) hasGid;
- (BOOL) hasAttrId;
- (BOOL) hasGiftCount;
@property (readonly) SInt32 owid;
@property (readonly, strong) User* user;
@property (readonly, strong) User* anchor;
@property (readonly) SInt32 templateId;
@property (readonly) SInt32 gid;
@property (readonly) SInt32 attrId;
@property (readonly) SInt32 giftCount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BannerNotifyBuilder*) builder;
+ (BannerNotifyBuilder*) builder;
+ (BannerNotifyBuilder*) builderWithPrototype:(BannerNotify*) prototype;
- (BannerNotifyBuilder*) toBuilder;

+ (BannerNotify*) parseFromData:(NSData*) data;
+ (BannerNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BannerNotify*) parseFromInputStream:(NSInputStream*) input;
+ (BannerNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BannerNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BannerNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BannerNotifyBuilder : PBGeneratedMessageBuilder {
@private
  BannerNotify* resultBannerNotify;
}

- (BannerNotify*) defaultInstance;

- (BannerNotifyBuilder*) clear;
- (BannerNotifyBuilder*) clone;

- (BannerNotify*) build;
- (BannerNotify*) buildPartial;

- (BannerNotifyBuilder*) mergeFrom:(BannerNotify*) other;
- (BannerNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BannerNotifyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwid;
- (SInt32) owid;
- (BannerNotifyBuilder*) setOwid:(SInt32) value;
- (BannerNotifyBuilder*) clearOwid;

- (BOOL) hasUser;
- (User*) user;
- (BannerNotifyBuilder*) setUser:(User*) value;
- (BannerNotifyBuilder*) setUserBuilder:(UserBuilder*) builderForValue;
- (BannerNotifyBuilder*) mergeUser:(User*) value;
- (BannerNotifyBuilder*) clearUser;

- (BOOL) hasAnchor;
- (User*) anchor;
- (BannerNotifyBuilder*) setAnchor:(User*) value;
- (BannerNotifyBuilder*) setAnchorBuilder:(UserBuilder*) builderForValue;
- (BannerNotifyBuilder*) mergeAnchor:(User*) value;
- (BannerNotifyBuilder*) clearAnchor;

- (BOOL) hasTemplateId;
- (SInt32) templateId;
- (BannerNotifyBuilder*) setTemplateId:(SInt32) value;
- (BannerNotifyBuilder*) clearTemplateId;

- (BOOL) hasGid;
- (SInt32) gid;
- (BannerNotifyBuilder*) setGid:(SInt32) value;
- (BannerNotifyBuilder*) clearGid;

- (BOOL) hasAttrId;
- (SInt32) attrId;
- (BannerNotifyBuilder*) setAttrId:(SInt32) value;
- (BannerNotifyBuilder*) clearAttrId;

- (BOOL) hasGiftCount;
- (SInt32) giftCount;
- (BannerNotifyBuilder*) setGiftCount:(SInt32) value;
- (BannerNotifyBuilder*) clearGiftCount;
@end


// @@protoc_insertion_point(global_scope)
